runtime: custom
env: flex

runtime_config:
  document_root: public

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

skip_files:
  - .env.example
  - nginx.conf
  - init.sh
  - script.py
  - .devcontainer
  - .vagrant
  - .vscode

env_variables:
  APP_NAME: Laravel
  APP_ENV: local
  APP_KEY: base64:Tg7wXxVOVtl7K1y3gYtfhLWNLD5mBxN1Wy9y48985pY=
  APP_DEBUG: true
  APP_URL: http://localhost
  LOG_CHANNEL: stack
  DB_CONNECTION: mysql
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_DATABASE: db_procedure
  DB_USERNAME: t6w3r6k4_ascc
  DB_PASSWORD: Wy75ld57yz
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  SESSION_DRIVER: file
  SESSION_LIFETIME: 120
  QUEUE_DRIVER: sync
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: null
  REDIS_PORT: 6379
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PORT: 2525
  MAIL_USERNAME: null
  MAIL_PASSWORD: null
  MAIL_ENCRYPTION: null
  PUSHER_APP_ID:
  PUSHER_APP_KEY:
  PUSHER_APP_SECRET:
  PUSHER_APP_CLUSTER: mt1
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
  DB_SOCKET: "/cloudsql/haz-conta:us-east1:haz-conta-instance-development"

beta_settings:
  cloud_sql_instances: "haz-conta:us-east1:haz-conta-instance-development"